ui/things/urls.py
from django.urls import path
from django.views.generic import TemplateView
from things import views

app_name='things'
urlpatterns=[
    path('',views.index,name='index'),
    path('about/',TemplateView.as_view(template_name='things/gallery.html'),name='about'),
    path('<int:item_id>',views.detail,name='detail'),
    path('',views.item,name='item'),
    path('',views.req,name='req'),
    path('register/',views.register,name='register'),
    path('registerd/',views.registerd,name='registerd'),
    path('user_login/',views.user_login,name='user_login'),
    path('',views.create_item,name='create_item'),
    path('',views.add_item,name='add_item'),
    path('satreq/<int:id>/',views.delete_item,name='delete_item'),
    path('satreq2/<int:id>/',views.delete_item2,name='delete_item2'),
]

ui/ui/urls.py
from django.contrib import admin
from django.urls import path,include
from things import views

urlpatterns = [
    path('index.html',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('things/',include('things.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

ui/things/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from location_field.models.plain import PlainLocationField
# Create your models here.
WORK_CHOICES=(
    ("1", "Individual"),
    ("2", "Organisation"),
)
EMP_CHOICES=(
    ("1", "Employed"),
    ("2", "Unemployed"),
)
AFF_CHOICES=(
    ("1", "Yes"),
    ("2", "No"),
)

class Donor(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=256)
    email=models.EmailField(max_length=256)
    age=models.PositiveIntegerField()
    phoneno=PhoneField(blank=True,help_text='Contact phone number')
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    image=models.CharField(max_length=500,default='')
    choice=models.CharField(
        max_length = 20,
        choices = WORK_CHOICES,
        default = '1'
    )
    description=models.TextField()

class Donee(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    doname=models.CharField(max_length=256)
    doemail=models.EmailField(max_length=256)
    age=models.PositiveIntegerField()
    dophoneno=PhoneField(blank=True,help_text='Contact phone number')
    income=models.PositiveIntegerField()
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    dchoice=models.CharField(
        max_length = 20,
        choices = WORK_CHOICES,
        default = '1'
    )
    employment_status=models.CharField(
        max_length = 20,
        choices = EMP_CHOICES,
        default = '1'
    )
    affilated_with_NGO=models.CharField(
        max_length = 20,
        choices = AFF_CHOICES,
        default = '1'
    )

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name=models.CharField(max_length=200)
    item_quantity=models.PositiveIntegerField()
    item_image=models.CharField(max_length=500,default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F3%2F34%2FNokia_3310_3G_%252820180116%2529.jpg&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFeature_phone&tbnid=FjmqN9PVVRY7zM&vet=12ahUKEwibhsOs95XrAhV6k0sFHWCbBBEQMygHegUIARDyAQ..i&docid=Jtq_cpENzKzFCM&w=2166&h=2327&q=phone&ved=2ahUKEwibhsOs95XrAhV6k0sFHWCbBBEQMygHegUIARDyAQ')
    item_desc=models.TextField()

class Requirement(models.Model):

    def __str__(self):
        return self.requirement_name

    requirement_name=models.CharField(max_length=200)
    requirement_quantity=models.PositiveIntegerField()
    requirement_desc=models.TextField()

ui/things/forms.py
from django import forms
from .models import Donee,Donor,Item,Requirement
from passwords.validators import (DictionaryValidator, LengthValidator, ComplexityValidator)

class DonorForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=Donor
        fields="__all__"

class DoneeForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=Donee
        fields="__all__"

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields="__all__"

class RequirementForm(forms.ModelForm):
    class Meta:
        model=Requirement
        fields="__all__"

ui/things/views.py
from django.shortcuts import render,redirect
from .forms import DonorForm,DoneeForm,ItemForm,RequirementForm
# Create your views here.
from .models import Item,Requirement
from django.views.generic import TemplateView
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

class GalleryView(TemplateView):
    template_name = "things/gallery.html"

def index(request):
    return render(request,'things/index.html')

@login_required
def special(request):
    return HttpResponse("Your logged in,Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def registerd(request):
    registered=False

    if request.method=='POST':
        user_form=DoneeForm(data=request.POST)


        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            registered=True
        else:
            print(user_form.errors)
    else:
        user_form=DoneeForm()

    return render(request,'things/doneeform.html',{'user_form':user_form,'registered':registered})

def register(request):
    registered=False

    if request.method=='POST':
        profile_form=DonorForm(data=request.POST)


        if profile_form.is_valid():
            user=profile_form.save()
            user.set_password(user.password)
            user.save()

            registered=True
        else:
            print(profile_form.errors)
    else:
        profile_form=DonorForm()

    return render(request,'things/donorform.html',{'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method=='POST':
        email=request.POST.get('email')
        password=request.POST.get('password')
        doemail=request.POST.get('doemail')
        dopassword=request.POST.get('dopassword')


        user=authenticate(email=email,password=password)
        userd=authenticate(doemail=doemail,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        elif userd:
            if userd.is_active:
                login(request,userd)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username : {} and Password: {}".format(email,password))
            return HttpResponse("Invalid login details!")
    else:
        return render(request,'things\login.html',{})

def create_item(request):
    if request.method=='POST':
        form=ItemForm(data=request.POST)
        if form.is_valid():
            form.save()
    else:
        form=ItemForm()

    return render(request,'things/item-form.html',{'form':form})

def add_item(request):
    req_form=RequirementForm(request.POST)

    if req_form.is_valid():
        req_form.save()
        return redirect('things:index')

    return render(request,'things/requirement-form.html',{'req_form':req_form})

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'things/detail.html',context)

def detaild(request,req_id):
    req=Requirement.objects.get(pk=req_id)
    context={
        'req':req,
    }
    return render(request,'things/detaild.html',context)

def item(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request,'things/donors.html',context)

def req(request):
    req_list=Requirement.objects.all()
    context={
        'req_list':req_list,
    }
    return render(request,'things/donees.html',context)

def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method=='POST':
        item.delete()
        return redirect('things:index')

    return render(request,'things/item-need.html',{'item':item})

def delete_item2(request,id):
    req=Requirement.objects.get(id=id)
    if request.method=='POST':
        req.delete()
        return redirect('things:index')

    return render(request,'things/item-donate.html',{'req':req})

ui/things/templates/things/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="login.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <div class="navbar-nav">
       <a class="navbar-brand" href="{% url 'index' %}">UI</a>
       <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
       <a class="nav-item nav-link" href="{% url 'things:register' %}">Register for Donor</a>
       <a class="nav-item nav-link" href="{% url 'things:registerd' %}">Register for Donee</a>
       <a class="nav-item nav-link" href="{% url 'things:item' %}">Donations</a>
       <a class="nav-item nav-link" href="{% url 'things:req'  %}">Requirements</a>
       {% if user.is_authenticated or userd.is_authenticated %}
       <a class="nav-item navbar-link" href="{% url 'logout' %}">Logout</a>
       {% else %}
       <a class="navbar-link nav-item" href="{% url 'things:user_login' %}">Login</a>
       {% endif %}
       {% if user.is_authenticated %}
       <a class="nav-item nav-link" href="{% url 'things:create_item' %}">Add Item</a>
       {% endif %}
       {% if userd.is_authenticated %}
       <a class="nav-item nav-link" href="{% url 'things:add_item' %}">Requirement Item</a>
       {% endif %}
     </div>
   </nav>

   <div class="container">
   {% block body_block %}
   {% endblock %}
   </div>


  </body>
</html>

ui/things/templates/things/detail.html
{% extends 'things/base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img height="300px" src="{{ item.item_image}}" class="card">
    </div>
    <div class="col-md-6">
      <h1>{{ item.item_name }}</h1>
      <h2>{{ item.item_desc }}</h2>
      <h3>{{ item.item_quantity }}</h3>
      <a href="{% url 'things:delete_item' item.id %}">I need</a>
    </div>

  </div>
</div>

{% endblock %}

ui/things/templates/things/detaild.html
{% extends 'things/base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <h1>{{ req.requirement_name }}</h1>
    </div>
    <div class="col-md-6">

      <h2>{{ req.requirement_desc }}</h2>
      <h3>{{ req.req_quantity }}</h3>
      <a href="{% url 'things:delete_item2' req.id %}">Donate</a>
    </div>

  </div>
</div>

{% endblock %}

ui/things/templates/things/donors.html
{% extends 'things/base.html' %}
{% load static %}
    {% block body %}
    {% for item in item_list %}
    <div class="row">
      <div class="col-md-3 offset-md-2">
        <img src="{{ item.item_image }}" class="card" height="150px" alt="">
      </div>
      <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc }}</h5>
        <h6>{{ item.item_quantity }}</h6>
      </div>
      <div class="col-md-2">
        <a href="{% url 'things:detail' item.id %}" class="btn btn-success">Details</a>
      </div>
    </div>
    {% endfor %}
    {% endblock %}
  

ui/things/templates/things/gallery.html
{% extends 'things/base.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/gallery_style.css' %}">
    <style>
      .row-header{
    margin: 0px auto;
    padding: 0px auto;
}

.row-content {
    margin: 0px;
    padding: 50px 0px 50px 0px;
    border-bottom: 1px ridge;
    min-height: 400px;
}

.footer {
    background-color: black ;
    color: azure;
    margin: 0px auto;
    padding: 20px 0px 20px 0px;
    max-width: 100%;
}

.jumbotron {
    padding:70px 30px 70px 30px;
    margin:0px auto;
    background:#eb4326 ;
    ;
    color:floralwhite;
}

address{
    font-size:80%;
    margin:0px;
    color:#0f0f0f;
}

.navbar{
    background-color: black;
}

body{
    padding: 50px 0px 0px 0px;
    z-index: 0;
}

.card-header{
    background-color:grey;
}

.tab-content {
    border-left: 1px solid #ddd;
    border-right: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
    padding: 10px;
}

.carousel {
    background: white;
}

.carousel-item {
  height: 300px;
}

.carousel-item img {
    position: absolute;
    top: 0;
    left: 0;
    min-height: 300px;
}

#carouselButton {
    right:15px;
    position: absolute;
    bottom: 0px;
    z-index: 1;
}

.ngo {
    color: #ffffff;
    margin : 20px auto;
    padding: 0px;
    background-color: #E1EDED;
    }

.ngo h2{
    text-align: center;
    color: black;
    }

    /*figure{
        display: inline-block;
    }*/
.column {
      float: left;
      width: 33.33%;
      padding: 5px;
    }

    /* Clearfix (clear floats) */
.row::after {
      content: "";
      clear: both;
      display: table;
    }
 #image img {
        max-width: 100%;
          height: auto;
          width: 200px;
        }

.btn {
    margin: auto;
    padding: auto;
    background-color: white;
}

#partner {
    text-align: center;
    }

    #feedback {
    margin: 10px;
    }

    .carousel-inner img {
        width: 100%;
        /*max-width: 1rem;*/
        height: 55%;
      }

    .carousel-control-prev, .carousel-control-next{
        bottom: 25;
    }

    h4 {
        color: #691838;
        font-weight: bold;
    }
  .main-head{
    margin: 20px auto;
  }
  body{
  background-color: #C8C8C8;
}
.container-img-gal{
  max-width: 1200px;
  margin: auto;
  background: #f2f2f2;
  overflow: auto;
}
.gallery{
  margin:5px;
  border:1px solid #ccc;
  float:left;
  width: 500px;
}
.gallery img{
  width:100%;
  height: auto;
}

    </style>

    <title>U & I: Gallery</title>

</head>

<body>
  <nav class="navbar navbar-dark navbar-expand-sm fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="botton" data-toggle="collapse" data-target=#navbar>
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand mr-auto" href="{% url 'index' %}"><img src="{% static 'images/logo.jpg' %}" height="30" width="41"></a>
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}"><span class="fa fa-home fa-lg"></span> Home</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'things:about' %}"><span class="fa fa-picture-o fa-lg"></span> Gallery</a></li>
          </ul>
          <span class="navbar-text">
              <a id="loginModalOpen" href="{% url 'things:user_login' %}" role="button">
              <span class="fa fa-sign-in"></span> Login</a>
            </span>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="main-head">
        <h1>A little help, can go a long way....</h1>
      </div>
      <div class="container-img-gal">
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img1.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img2.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img3.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img4.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img5.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img-6.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img-7.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img-8.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img-9.jpg' %}" alt="">
        </div>
        <div class="gallery">
          <img src="{% static 'images/Images_Gallery/img-10.jpg' %}" alt="">
        </div>
      </div>

    </div>
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
</body>
{% endblock %}


</body>
</html>
{% block body %}
{% for item in item_list %}
<div class="row">
<div class="col-md-3 offset-md-2">
 <img src="{{ item.item_image }}" class="card" height="150px" alt="">
</div>
<div class="col-md-4">
 <h3>{{ item.item_name }}</h3>
 <h5>{{ item.item_desc }}</h5>
 <h6>{{ item.item_quantity }}</h6>
</div>
<div class="col-md-2">
 <a href="{% url 'things:detail' item.id %}" class="btn btn-success">Details</a>
</div>
</div>
{% endfor %}

 {% for req in req_list %}
 <div class="row">
   <div class="col-md-4">
     <h3>{{ req.requirement_name }}</h3>
     <h5>{{ req.requirement_desc }}</h5>
     <h6>{{ req.requirement_quantity }}</h6>
   </div>
   <div class="col-md-2">
     <a href="{% url 'things:detaild' req.id %}" class="btn btn-success">Details</a>
   </div>
 </div>
{% endfor %}
{% endblock %}

ui/things/templates/things/index.html
{% extends 'things/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block body_block %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <style>
    .row-header{
  margin: 0px auto;
  padding: 0px auto;
}

.row-content {
  margin: 0px;
  padding: 50px 0px 50px 0px;
  border-bottom: 1px ridge;
  min-height: 400px;
}

.footer {
  background-color: black ;
  color: azure;
  margin: 0px auto;
  padding: 20px 0px 20px 0px;
  max-width: 100%;
}

.jumbotron {
  padding:70px 30px 70px 30px;
  margin:0px auto;
  background:#eb4326 ;
  ;
  color:floralwhite;
}

address{
  font-size:80%;
  margin:0px;
  color:#0f0f0f;
}

.navbar{
  background-color: black;
}

body{
  padding: 50px 0px 0px 0px;
  z-index: 0;
}

.card-header{
  background-color:grey;
}

.tab-content {
  border-left: 1px solid #ddd;
  border-right: 1px solid #ddd;
  border-bottom: 1px solid #ddd;
  padding: 10px;
}

.carousel {
  background: white;
}

.carousel-item {
height: 300px;
}

.carousel-item img {
  position: absolute;
  top: 0;
  left: 0;
  min-height: 300px;
}

#carouselButton {
  right:15px;
  position: absolute;
  bottom: 0px;
  z-index: 1;
}

.ngo {
  color: #ffffff;
  margin : 20px auto;
  padding: 0px;
  background-color: #E1EDED;
  }

.ngo h2{
  text-align: center;
  color: black;
  }

  /*figure{
      display: inline-block;
  }*/
.column {
    float: left;
    width: 33.33%;
    padding: 5px;
  }

  /* Clearfix (clear floats) */
.row::after {
    content: "";
    clear: both;
    display: table;
  }
#image img {
      max-width: 100%;
        height: auto;
        width: 200px;
      }

.btn {
  margin: auto;
  padding: auto;
  background-color: white;
}

#partner {
  text-align: center;
  }

  #feedback {
  margin: 10px;
  }

  .carousel-inner img {
      width: 100%;
      /*max-width: 1rem;*/
      height: 55%;
    }

  .carousel-control-prev, .carousel-control-next{
      bottom: 25;
  }

  h4 {
      color: #691838;
      font-weight: bold;
  }
.main-head{
  margin: 20px auto;
}

    </style>

    <title>U & I: Index</title>

</head>

<body>
    <header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-sm-12" style="text-align: center;">
                    <h1 style= "text-align: center;" >About Us</h1>
                    <p>U&I is a volunteer-driven charitable organization based in Bangalore, India.
                        This platform is used by NGOs to get the help they need from donors. This helps empower NGOs to receive goods in good condition (clothes,laptops etc.) for the betterment of the community they work with while giving the donors a chance to responsibly give away their unwanted/excess items.</p>
                </div>
                <div class="col-12 col-sm align-self-center">
                    <img src="" class="img-fluid">
                </div>
            </div>
        </div>
    </header>
    <div class="container">
    <div class="row row-content">
        <div class="col">
          <div id="mycarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="{% static 'images/donate.jpg' %}" alt="Donate">
                <div class="carousel-caption d-none d-md-block"> </div>
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="{% static 'images/donate 2.jpg'%}" alt="Children">
                <div class="carousel-caption d-none d-md-block"> </div>
              </div>
              <div class="carousel-item">
                <img class="img-fluid align-self-center" src="{% static 'images/share.jpg'%}" alt="share">
                <div class="carousel-caption d-none d-md-block"> </div>
              </div>
            <ol class="carousel-indicators">
              <li data-target="#mycarousel" data-slide-to="0" class="active"></li>
              <li data-target="#mycarousel" data-slide-to="1"></li>
              <li data-target="#mycarousel" data-slide-to="2"></li>
            </ol>
          </div>
          <a class="carousel-control-prev" href="#mycarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#mycarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
      </div>
    </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-sm-12" style="text-align: center;">
                    <h1 style= "text-align: center;" >Why you should donate</h1>
                    <p>
                        By donating to our general fund, this enables us to wisely use the resources where the greatest need is at any particular time. By delivering help on the ground through our project partnerships we can help change lives by meeting their basic needs.Our projects are designed to empower greater self-sufficiency, new hope and a more sustainable future.
                    </p>
                    <p>
                        Wanna know more about donations? Check Out <a href="https://www.1millionwomen.com.au/blog/the-pros-and-cons-of-donating-clothes-to-charity/">Pros and cons of donation</a>
                    </p>
                </div>
                <div class="col-12 col-sm align-self-center">
                    <img src="" class="img-fluid">
                </div>
            </div>
            <div class="col-12 col-sm-12" style="text-align: center;">
            <button type="button" class="btn btn-default" style="text-align: center;"> <a href="{% url 'things:user_login' %}">Donate Now</a></button>
            </div>
        </div>
    </div>

    <div class="ngo">
        <h2>Our Partners</h2>
        <div class="row col-12 text-center" id="image">
        <div class="column">
        <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="column">
        <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="column">
        <img src="{% static 'images/logo.png' %}">
        </div>
        <div class="column">
            <img src="{% static 'images/logo.png' %}">
            </div>
            <div class="column">
            <img src="{% static 'images/logo.png' %}">
            </div>
            <div class="column">
            <img src="{% static 'images/logo.png' %}">
            </div>
        </div>
    </div>

    <div class="container">
        <h4 id="partner" class="">What Our Partners Think</h4>
        <div id="feedback" class="carousel slide" data-ride="carousel" data-interval="3000">

        <!-- Indicators -->
        <ul class="carousel-indicators">
        <li data-target="#feedback" data-slide-to="0" class="active"></li>
           <li data-target="#feedback" data-slide-to="1"></li>
           <li data-target="#feedback" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner align-self-center center id="car">
           <div class="carousel-item active">
            <!-- <p>dwgk yf8oeifb ytywoidvh hjywihdgj </p> -->
            <img src="{% static 'images/feedback.jpg' %}">
           </div>
           <div class="carousel-item">
            <!-- <p>wudiw djkgwduvd dhfwuidhc dgfidugvd</p> -->
            <img src="{% static 'images/feedback.jpg' %}">
           </div>
           <div class="carousel-item">
            <!-- <p> gdug hehf rishika sneha vasantha</p> -->
            <img src="{% static 'images/feedback.jpg' %}">
           </div>
        </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#feedback" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>

          <a class="carousel-control-next" href="#feedback" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>

    </div>

</body>
<footer class="footer">
    <div class="container">
      <div class="row">

        <div class="col-6 offset-5 col-sm-2 text-center">
          <h5>Our Address</h5>
          <div>
            VNR VJIET,
            Bachupally, Hyderabad, INDIA
            <i class="fa fa-phone fa-lg"></i>: +852 1234 5678
            <i class="fa fa-fax fa-lg"></i>: +852 8765 4321
            <i class="fa fa-envelope fa-lg"></i>:
            <a href="mailto:confusion@food.net">abc@gmail.com</a>
          </div>
        </div>
     </div>

    </div>
  </footer>
     <!--jQuery first, then Popper.js, then Bootstrap JS.-->
  <script src="node_modules/jquery/dist/jquery.slim.min.js"></script>
  <script src="node_modules/popper.js/dist/umd/popper.min.js"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>


</html>

{% endblock %}